---
version: "3.7"
services:

  # ---------------------------------------------------------------------
  # | Nginx-Service                                                     |
  # ---------------------------------------------------------------------
  static-website:
    build:
      context: ../backend/static-website
      dockerfile: static-website.Dockerfile
    container_name: static-website
    restart: unless-stopped
    volumes:
      - ../frontend/static-website/dist:/usr/share/static-website/html
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.static-website.entrypoints=web
      - traefik.http.routers.static-website.middlewares=test-redirectscheme
      - traefik.http.routers.static-website-secure.entrypoints=websecure
      - traefik.http.routers.static-website-secure.tls.certresolver=myresolver
      - traefik.http.routers.static-website-secure.tls=true
      - traefik.http.routers.static-website-secure.middlewares=test-compress,test-ratelimit,test-redirectscheme
      # Services
      - traefik.http.services.static-website-secure.loadbalancer.server.port=80
      # Middlewares
      - traefik.http.middlewares.test-compress.compress=true
      - traefik.http.middlewares.test-ratelimit.ratelimit.average=2
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.port=443
