---
version: "3.7"
services:

  # ---------------------------------------------------------------------
  # | Nginx-Service                                                     |
  # ---------------------------------------------------------------------
  nginx:
    build:
      context: ../backend/nginx
      dockerfile: nginx.Dockerfile
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ../frontend/nginx/dist:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.nginx.entrypoints=web
      - traefik.http.routers.nginx.middlewares=test-redirectscheme
      - traefik.http.routers.nginx-secure.entrypoints=websecure
      - traefik.http.routers.nginx-secure.tls.certresolver=myresolver
      - traefik.http.routers.nginx-secure.tls=true
      - traefik.http.routers.nginx-secure.middlewares=test-compress,test-ratelimit,test-redirectscheme
      # Services
      - traefik.http.services.nginx-secure.loadbalancer.server.port=80
      # Middlewares
      - traefik.http.middlewares.test-compress.compress=true
      - traefik.http.middlewares.test-ratelimit.ratelimit.average=2
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.port=443
